### ISSUE TITLE
404 on hercules-ci.053d17fe.js

### ISSUE THREAD

**Issue by o1lo01ol1o** [hercules-ci/support#11]
This is maybe a transitory failure, but I'm currently getting

`GET https://hercules-ci.com/assets/hercules-ci.053d17fe.js net::ERR_ABORTED 404` in Chrome.

If I go private or another browser, I get your homepage (how would I login from here?).

**Comment by roberth** [comment]
Thank you for reporting this issue. We are looking into it. It appears to be a caching issue and it tends to occur after deployments.
The home page will have an obvious login button when the product is ready for a broader audience. For now you may use https://hercules-ci.com/api/auth/github to log in.

**Comment by domenkozar** [comment]
This should be fixed now, please reopen if problem persists. Thanks for the report!
