### ISSUE TITLE
Instructions for deploying without nixops

### ISSUE THREAD

**Issue by offlinehacker** [hercules-ci/support#15]
Currently only instructions for deploying with `nixops` are provided. Since i'm more fan of terraform myself, as nixops does not provide all cloud features, it would be nice to include instructions how to provision without `nixops`. Configuration i use is very similar to nixops one, with a few differences:

```
{ modulesPath, ... }:

let
  hercules-ci-agent =
    builtins.fetchTarball "https://github.com/hercules-ci/hercules-ci-agent/archive/stable.tar.gz";
in {
  imports = [
    (hercules-ci-agent + "/profile.nix")
  ];

  services.hercules-ci-agent.clusterJoinTokenPath = "/var/keys/agent-token";
  users.extraUsers.hercules-ci-agent.extraGroups = [ "keys"  ];
```

Here is terraform example on how to deploy hercules-ci agent on google cloud:

https://github.com/xtruder/tf-hercules-ci-agent-gcloud

**Comment by domenkozar** [comment]
Nice! We plan to support terraform, but https://github.com/hercules-ci/hercules-ci-agent/issues/33 as the absolute minimum.

**Comment by roberth** [comment]
[NixOS-only instructions](https://docs.hercules-ci.com/#deploy-with-nixos) are now available.

[Instructions with a manual configuration file](https://docs.hercules-ci.com/#deploy-manually-with-a-configuration-file) are also available. The cache setup instructions are not up to par yet for this one. Ping us if you need help.

(For nix-darwin, follow the instructions in the web app: https://hercules.ci.com/dashboard)

**Comment by offlinehacker** [comment]
You could integrate instructions for terraform, as for many real deployments nixops is insufficient. I'm going to close this issue, as I think it's fixed now. Thanks 🙂
