### ISSUE TITLE
Failed to load error

### ISSUE THREAD

**Issue by offlinehacker** [hercules-ci/support#18]
I am testing `hercules-ci` with https://github.com/xtruder/kubenix/tree/kubenix-2.0, but i'm getting this error now:

![Screenshot](https://user-images.githubusercontent.com/585547/57193185-f3c2ea80-6f38-11e9-8de8-3d38b429d208.png)

After logging out it started to work again, so it's transient, but it was annoying before i figured it out.

**Comment by roberth** [comment]
This looks like it may be a symptom of the logouts #13, but if that's the case, we need to handle the 401 or 404 appropriately, checking auth status and offering to log in.

**Comment by domenkozar** [comment]
Fixed a long time ago.
