### ISSUE TITLE
Open source jobs page is only accessible to collaborators

### ISSUE THREAD

**Issue by roberth** [hercules-ci/support#20]

**Comment by domenkozar** [comment]
The job page is now public, although one can't browse jobs/repos/accounts yet.

**Comment by nh2** [comment]
> The job page is now public

Should I be able to see https://hercules-ci.com/github/nh2/static-haskell-nix/jobs as a non-logged-in user?

**Comment by chrissound** [comment]
This seems to be working / implemented now. For example https://hercules-ci.com/github/chrissound/SodiumSierraStrawberry / https://hercules-ci.com/github/chrissound/SodiumSierraStrawberry/jobs/3 is publicly accessible.

Thanks!
