### ISSUE TITLE
Faster installation of hercules-ci-agent

### ISSUE THREAD

**Issue by offlinehacker** [hercules-ci/support#25]
Currently installation of hercules-ci takes a long time, as it has to compile it from source. It would be nice to have agent installation cached by cachix. Having instructions in documentation to add required cache would be nice :)

**Comment by domenkozar** [comment]
Yup. Refs https://github.com/hercules-ci/hercules-ci-agent/issues/32

**Comment by domenkozar** [comment]
Shipped as part of hercules-ci-agent 0.3.1.

There is note in the deployment step. [An example](https://docs.hercules-ci.com/hercules-ci/getting-started/deploy/nixops/#_5_deploy).
