### ISSUE TITLE
Continuous Delivery

### ISSUE THREAD

**Issue by o1lo01ol1o** [hercules-ci/support#32]
Hi,
 Is there any planned support for nix-based continuous delivery?  

By way of background, we currently use gitlab-runners in conjunction with a `hydra` build farm to perform `nix-copy` and a handful of `ssh` and `scp` commands when specified branches are updated.  However, the lack of caching on the runner makes this a time-consuming process as it has to copy every derivation on each deployment.  It also requires that our configuration be additionally spread across gitlab CI variables.   

Given that we can mirror a repository on Github fairly easily, it seems like CD would be cleaner if handled in a native `nix` solution.

**Comment by domenkozar** [comment]
Yes, see #3

**Comment by roberth** [comment]
Implemented as "Effects" but changes will be limited at this point. https://docs.hercules-ci.com/hercules-ci/effects/
