### ISSUE TITLE
Recursively build attrs

### ISSUE THREAD

**Issue by mkg20001** [hercules-ci/support#42]
I have a [ci.nix](https://github.com/mercode-org/meros-nix/blob/master/ci.nix) that looks roughly like this:

```nix
{
  someAttr = {
    drv = ...;
    otherDrv = ...;
  };
}
```

The derivations aren't getting built if they're nested deeper than one key. Is there any way to solve that?

**Comment by roberth** [comment]
Yes, for example

```
let
  # import from nixpkgs/lib or
  recurseIntoAttrs = as: as // { recurseForDerivations = true; };
in
{
  someAttr = recurseIntoAttrs {
    drv = ...;
    otherDrv = ...;
  };
}
```

See also https://docs.hercules-ci.com/hercules-ci/reference/evaluation/

or if you're creating a build matrix, [`dimension`](https://github.com/hercules-ci/project.nix/blob/master/lib/dimension.nix) may be nice and also sets this.

The reason this special attribute is required, is for compatibility with `nix-build`.

**Comment by mkg20001** [comment]
Ok, thx
