### ISSUE TITLE
Where should agent.toml go in NixOS?

### ISSUE THREAD

**Issue by srid** [hercules-ci/support#45]
I wanted to setup the CI to use my cachix cache, but it is quite difficult to find the steps to do this. It seems I need to create a `binary-caches.json` file, but where do I specify it? `agent.toml` per [the docs](https://docs.hercules-ci.com/hercules-ci/reference/agent-config/#binaryCachesPath), but where should this `agent.toml` go?

This is how I've setup the agent:

```nix
  services.hercules-ci-agent = {
    enable = true;
    concurrentTasks = 4; # Number of jobs to run
    patchNix = true;
  };
```

**Comment by srid** [comment]
Note I originally tried `binaryCachesFile` by looking [at the source](https://github.com/hercules-ci/hercules-ci-agent/blob/2d4574b0b7723429b0416ca385c45a3ef072d973/tests/module-nixos/configuration-3-nixops-binaryCachesFile.nix#L6) - but it seems that key doesn't work anymore.

**Comment by srid** [comment]
Ah, okay. So I have to put this file manually under `/var/lib/hercules-ci-agent`. Still, I think the docs could have been improved in guide/tutorial side ("How to enable pushing to cachix cache", etc.).

**Comment by roberth** [comment]
Hi srid, thanks so much for reporting this issue. I'm glad you were able to resolve it, and I have made some improvements to the docs and test case.
