### ISSUE TITLE
Pricing Feedback

### ISSUE THREAD

**Issue by brendanhay** [hercules-ci/support#48]
Your current pricing of 29 EUR / active user / month seems insanely high relative to other CI providers in the space. Considering all the other providers also offer build hosts and caching, albeit limited, Hercules' does not. The value proposition from my perspective is the native Nix build coordination, caching, and GitHub PR integration, with emphasis on the coordination part.

For a rough comparison:

* Cirrus: 10 USD / user / month. 
* GitLab Hosted: 19 USD / user / month. (10K minutes)
* Travis: 63 USD / flat fee / month. (2 concurrent jobs)
* Circle: 30 / flat fee / month. (+ credits)

I'd like to use Hercules CI on a couple of private repositories which each have a handful active contributors - in one case it's 2 active developers so 67~ USD / month. In another case the repository in question has configuration and documentation that is constantly updated by non-technical personnel - the additional cost here is roughly 200~ USD / month. So assuming we don't have others at the company committing every other month-  the estimated total cost is more than 267~ USD / month.

An additional point is that although the Hercules CI agent setup is pretty painless (nice work) since I already have a couple of bare metal servers setup for CI purposes - for that monthly price I may as well bite the bullet and just use Hydra, despite the comparative inconvenience.

FWIW I think it's a great product and I'd be more than happy to throw money at it - but I'm unable to financially justify the price to those who hold the purse strings.

**Comment by roberth** [comment]
Hi Brendan, thank you for your feedback.

Although the current price is worth every penny, I am considering options to make it more attractive to those who are more focused on the relative price. More on that soon.

Regarding the config/docs committers. I have two new behaviors in mind:
 - allow configurable paths to be skipped. A commit/push is skipped if all changes are within the excluded paths and skipped jobs don't count towards active users.
 - restrict usage to configurable GitHub teams

These seem to solve the problem with active user count. Do you have a preference?

**Comment by brendanhay** [comment]
My main concern is bounding the cost - aka predicting fixed costs month on month. Having configurable ignores would work but requires care as someone without knowledge inadvertantly committing a whitespace change (ie. by formatting on git hook)  results in your monthly costing unexpectedly spiking. The configurable GitHub teams would avoid this, but I do think having a generalised configuration is probably more desirable (and easier to reason about) than tying it to separate GitHub team management and incantations.

So between your two outlined options I think in repository or nix configuration of ignored paths is probably preferable, assuming it's used with care and appropriate caveats. Maybe some kind of branch filter would also be desirable/useful here.

(No doubt you've considered other pricing options but paying `c * agent * repository` or similar seems more predictable.)

**Comment by roberth** [comment]
Changes are coming soon. I'll close this issue for now.
Thanks again.
