### ISSUE TITLE
Document effects

### ISSUE THREAD

**Issue by nrdxp** [hercules-ci/support#53]
I see effects are in beta, but I have absolutely no idea how to use them, or what they even do exactly. There should probably be a page added to the doc to explain their usage.

**Comment by roberth** [comment]
:100: It's been a private (ish) beta so far and I'd been wanting to overhaul the docs site. I've decided to skip that. You can expect documentation to land in the coming week or so.

**Comment by roberth** [comment]
Docs are available!

General introduction: https://docs.hercules-ci.com/hercules-ci/effects/
`hercules-ci-effects` repo intro: https://docs.hercules-ci.com/hercules-ci-effects/

Let me know if you have any questions or suggestions.

(It now also has an "Edit this Page" link on the top right, but I'll be happy to make changes myself)
