### ISSUE TITLE
Adding `flake.nix` doesn't trigger first build

### ISSUE THREAD

**Issue by brainrake** [hercules-ci/support#64]
Need to push `ci.nix` or `default.nix` to trigger first build.

**Comment by roberth** [comment]
I couldn't reproduce a problem with `flake.nix` specifically. Did you observe this right after installation, before pushing anything new? Installation currently does not trigger a job.

**Comment by brainrake** [comment]
After adding repository with a `flake.nix` (but no `ci.nix` or `default.nix`) on Hercules dashboard and pushing a new commit, the dashboard still says "Push a commit [with a Nix file](https://docs.hercules-ci.com/hercules-ci/getting-started/repository) to start the first job.". If I push an empty `ci.nix`, the build starts.

**Comment by brainrake** [comment]
After removing `ci.nix`, the project continues building with just `flake.nix`. It seems `ci.nix` is needed just to start the first job, `flake.nix` alone is not enough.

**Comment by brainrake** [comment]
Could not reproduce anymore. Seems fixed:)
