### ISSUE TITLE
500 error on Github sign in

### ISSUE THREAD

**Issue by Geometer1729** [hercules-ci/support#65]
When I try to sign in it says `sign in status unknown` and the sign in button remains. Whenever I try to view something non-public seemingly including dashboard it fails to load anything with `We made a request but the service encountered an error. (500)`

From the console log:
```
Status
500
Internal Server Error
VersionHTTP/3
Transferred703 B (20 B size)
Referrer Policystrict-origin-when-cross-origin
```

Unsurprisingly clearing cookies switching browsers and switching devices all don't help.
Revoking and reauthorizing hercules-ci with GitHub doesn't help.
If more info would be helpful just let me know how to collect it.

**Comment by roberth** [comment]
I've deployed a fix to better tolerate suspended GitHub App installations.
Does it fix the problem for you?

**Comment by Geometer1729** [comment]
> I've deployed a fix to better tolerate suspended GitHub App installations. Does it fix the problem for you?

It does. Thanks so much!
